### ISSUE TITLE
direction of line

### ISSUE THREAD

**Issue by CharlotteRdn** [lifeeka/leaflet.bezier#14]
I have set up a map with react-native via Expo. 

Currently, the flights / tracks work very well with the leaflet and the "bezier" module. However, when i tried to make a flight Honolulu -> Tokyo , the route was not right. Indeed, it should be done from right to left (roughly the ends of the card) and not from left to right. 

I have no idea on how I can set up this, do you have any clue ? Thanks a lot !

**Comment by spmsupun** [comment]
sorry for the late reply, hope you figured it out.
