### ISSUE TITLE
showing truck icon instead of default plane icon

### ISSUE THREAD

**Issue by AmAngular** [lifeeka/leaflet.bezier#16]
Hi everyone
i'm using leaflet.bezier with ngx-leaflet in my angular project and i want show truck icon instead plane icon from side view but when drawed curve line is like valley my truck has incorrect rotate

![123477962-0f574680-d614-11eb-93cc-230e457b8de5](https://user-images.githubusercontent.com/44199773/123482077-ecc82c00-d619-11eb-91b8-6099af506716.png)

**Comment by spmsupun** [comment]
I am not quite sure what you said, could you explain more?

**Comment by AmAngular** [comment]
In your demo example you were showing animated plane from 'top' view.
But in my case i need to show truck icon from 'side' view
And when doing this scenario cuases two different mode
1. If curve line is bulgy everything is ok.
2. but if curve line has "u" shape (🙃) truck icon display  in reverse view (as showing in 
https://github.com/lifeeka/leaflet.bezier/issues/16#issue-930484114)

**Comment by spmsupun** [comment]
well, right there is no option to achieve that since it was not originally designed to move a vehicle. but pull requests are welcome.
