### ISSUE TITLE
Animations seem to stop half way through

### ISSUE THREAD

**Issue by pachacamac** [lifeeka/leaflet.bezier#3]
~~As seen in the Demo, the planes only go about half way over the curve while they should go from beginning to end.~~ (sorry only now seen the closed issue. But I found the [position in the code](https://github.com/lifeeka/leaflet.bezier/blob/master/src/leaflet.bezier.js#L125) to change it)

~~Also is it possible to make the animation repeat somehow?~~ also figured out that. Changed the `setAnimatePlane` function to:

    setAnimatePlane: function setAnimatePlane(path) {
        if (this.spaceship_img) this.spaceship_img.remove();
        var SnapSvg = Snap('.leaflet-overlay-pane>svg');
        var spaceship_img = this.spaceship_img = SnapSvg.image(this.icon.path).attr({ visibility: "hidden" });
        var spaceship = SnapSvg.group(spaceship_img);
        var flight_path = SnapSvg.path(path).attr({ 'fill': 'none', 'stroke': 'none' });
        var full_path_length = Snap.path.getTotalLength(flight_path);
        var width = full_path_length / 6 / this._map.getZoom();
        var height = full_path_length / 6 / this._map.getZoom();
        width = Math.min(Math.max(width, 30), 64);
        height = Math.min(Math.max(height, 30), 64);
        var last_step = 0;
        var anim = function(){
            Snap.animate(0, full_path_length, function (step) {
                spaceship_img.attr({ visibility: "visible" });
                spaceship_img.attr({ width: width, height: height });
                last_step = step;
                var moveToPoint = Snap.path.getPointAtLength(flight_path, step);
                var x = moveToPoint.x - width / 2;
                var y = moveToPoint.y - height / 2;
                spaceship.transform('translate(' + x + ',' + y + ') rotate(' + (moveToPoint.alpha - 90) + ', ' + width / 2 + ', ' + height / 2 + ')');
            }, 5000, mina.easeinout, function () {
                //done - repeat
                anim()
            });
        };
        anim();
    },

to achieve what I wanted. In case someone else needs it.

**Comment by spmsupun** [comment]
hi @pachacamac, like i said in #2  this is not an issue, I made it that way, and I am very welcome to accept a pull requests
