### ISSUE TITLE
Is there a way to bind popup to icon?

### ISSUE THREAD

**Issue by stefanuscc** [lifeeka/leaflet.bezier#6]
Is there a way to add different popup data for each icon like these image bellow?

I try to bind popup to bezier but layerGroup does not support popup. 
I also have tried to change it to featureGroup but the popup only appear on the main point.

![bezier](https://user-images.githubusercontent.com/23050235/54505739-c2cc2d80-496b-11e9-96f2-35a44330d9de.jpg)

**Comment by spmsupun** [comment]
Right now no, but you can send a PR
