### ISSUE TITLE
Import problems

### ISSUE THREAD

**Issue by PavloKuchereshko** [lifeeka/leaflet.bezier#7]
I use angular 7 and installed leaflet.bezier with `npm i leaflet.bezier --save` and then tried to use. Since I have standard leaflet imported like `import * as L from "leaflet";` so that L.bezier(...) didn't work, and I imported leaflet.bezier like `import * as LB from "leaflet";` but again LB.bezier(...) was unresolvable. So how to resolve and use it, help, please

**Comment by spmsupun** [comment]
did you get the error fixed ?
