### ISSUE TITLE
mid flight

### ISSUE THREAD

**Issue by WeeCoopTech** [lifeeka/leaflet.bezier#8]
Hello !! 

How can i set up the package to have the icon going all the way to the arrival point ? 

Thank you

**Comment by spmsupun** [comment]
This is not implemented yet

**Comment by WeeCoopTech** [comment]
Thanks for answering me !

**Comment by spmsupun** [comment]
@WeeCoopTech  I have added a new update and you can do this now  🙂

**Comment by CharlotteRdn** [comment]
Thanks a lot :)

**Comment by WeeCoopTech** [comment]
Great, thanks !
